# Generated by Django 6.0.4 on 2026-05-08 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fact_app', '0002_article_invoice_alter_invoice_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='price',
            new_name='unit_price',
        ),
        migrations.AddField(
            model_name='article',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='article',
            name='total_line',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='customer',
            name='age',
            field=models.CharField(blank=True, choices=[('0-18', '0-18'), ('18-30', '18-30'), ('30+', '30+')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_type',
            field=models.CharField(choices=[('R', 'RECIEPT'), ('P', 'PROFORMA INVOICE'), ('I', 'INVOICE')], default='I', max_length=1),
        ),
    ]
